// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SampleSuite.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SampleSuite.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddRemoveItems {
            get {
                return ResourceManager.GetString("AddRemoveItems", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string DataBinding {
            get {
                return ResourceManager.GetString("DataBinding", resourceCulture);
            }
        }
        
        internal static string EnterIndexValue {
            get {
                return ResourceManager.GetString("EnterIndexValue", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string FileIO {
            get {
                return ResourceManager.GetString("FileIO", resourceCulture);
            }
        }
        
        internal static string FileWrittenSuccessfully {
            get {
                return ResourceManager.GetString("FileWrittenSuccessfully", resourceCulture);
            }
        }
        
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        internal static string InvalidIndexValue {
            get {
                return ResourceManager.GetString("InvalidIndexValue", resourceCulture);
            }
        }
        
        internal static string IOWriteError {
            get {
                return ResourceManager.GetString("IOWriteError", resourceCulture);
            }
        }
        
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        internal static string ListBoxAddRemoveSampleDescription {
            get {
                return ResourceManager.GetString("ListBoxAddRemoveSampleDescription", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string ReadWrite {
            get {
                return ResourceManager.GetString("ReadWrite", resourceCulture);
            }
        }
        
        internal static string ReadWriteSampleDescription {
            get {
                return ResourceManager.GetString("ReadWriteSampleDescription", resourceCulture);
            }
        }
        
        internal static string SystemsAndSensors {
            get {
                return ResourceManager.GetString("SystemsAndSensors", resourceCulture);
            }
        }
        
        internal static string TableOfContentsGreeting {
            get {
                return ResourceManager.GetString("TableOfContentsGreeting", resourceCulture);
            }
        }
        
        internal static string TableOfContentsInstructions {
            get {
                return ResourceManager.GetString("TableOfContentsInstructions", resourceCulture);
            }
        }
        
        internal static string TableOfContentsTitle {
            get {
                return ResourceManager.GetString("TableOfContentsTitle", resourceCulture);
            }
        }
        
        internal static string UIControls {
            get {
                return ResourceManager.GetString("UIControls", resourceCulture);
            }
        }
        
        internal static string UnknownCategoryError {
            get {
                return ResourceManager.GetString("UnknownCategoryError", resourceCulture);
            }
        }
        
        internal static string MultiBinding {
            get {
                return ResourceManager.GetString("MultiBinding", resourceCulture);
            }
        }
        
        internal static string SingleBinding {
            get {
                return ResourceManager.GetString("SingleBinding", resourceCulture);
            }
        }
        
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        internal static string MultiBindingSampleDescription {
            get {
                return ResourceManager.GetString("MultiBindingSampleDescription", resourceCulture);
            }
        }
        
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        internal static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        internal static string SingleBindingSampleDescription {
            get {
                return ResourceManager.GetString("SingleBindingSampleDescription", resourceCulture);
            }
        }
        
        internal static string SourceObject {
            get {
                return ResourceManager.GetString("SourceObject", resourceCulture);
            }
        }
        
        internal static string TargetObject {
            get {
                return ResourceManager.GetString("TargetObject", resourceCulture);
            }
        }
        
        internal static string RootViews {
            get {
                return ResourceManager.GetString("RootViews", resourceCulture);
            }
        }
        
        internal static string RootViewSampleDescription {
            get {
                return ResourceManager.GetString("RootViewSampleDescription", resourceCulture);
            }
        }
        
        internal static string SingleView {
            get {
                return ResourceManager.GetString("SingleView", resourceCulture);
            }
        }
        
        internal static string SplitView {
            get {
                return ResourceManager.GetString("SplitView", resourceCulture);
            }
        }
        
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        internal static string TabbedSplitView {
            get {
                return ResourceManager.GetString("TabbedSplitView", resourceCulture);
            }
        }
        
        internal static string TabView {
            get {
                return ResourceManager.GetString("TabView", resourceCulture);
            }
        }
        
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        internal static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        internal static string Skew {
            get {
                return ResourceManager.GetString("Skew", resourceCulture);
            }
        }
        
        internal static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        internal static string TransformSampleDescription {
            get {
                return ResourceManager.GetString("TransformSampleDescription", resourceCulture);
            }
        }
        
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        internal static string ListBoxSectioningSampleDescription {
            get {
                return ResourceManager.GetString("ListBoxSectioningSampleDescription", resourceCulture);
            }
        }
        
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        internal static string Sectioning {
            get {
                return ResourceManager.GetString("Sectioning", resourceCulture);
            }
        }
        
        internal static string Brushes {
            get {
                return ResourceManager.GetString("Brushes", resourceCulture);
            }
        }
        
        internal static string BrushesSampleDescription {
            get {
                return ResourceManager.GetString("BrushesSampleDescription", resourceCulture);
            }
        }
    }
}
